### PR TITLE
Release tracking PR: `hex-conservative 0.3.0`

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release add a changelog entry, bump the version number, and update the lock files

### CODE REVIEW

**Comment by tcharding** [comment]
Includes a patch upfront to fix fuzz job.

**Comment by apoelstra** [comment]
Can you split the CI fix out? This crate doesn't have lockfiles which makes it hard for me to test version-changing PRs where different commits have different verions.

**Comment by tcharding** [comment]
No sweat, I can add lock files too if it helps?

**Comment by tcharding** [comment]
Patch 1 is now in #111

**Comment by apoelstra** [comment]
> No sweat, I can add lock files too if it helps?

This would be super helpful for me, yeah.

**Comment by tcharding** [comment]
Draft till #112 goes in

**Comment by apoelstra** [comment]
Is this ready for review?

**Comment by tcharding** [comment]
Waiting for #119 to merge please.

**Comment by apoelstra** [comment]
Done.

**Review by apoelstra — APPROVED** [review]
ACK f5d87a17a352428d3379126cd895297f66ffaf4b; successfully ran local tests; lots of stuff!

**Comment by apoelstra** [comment]
Tagged and published.

**Comment by tankyleo** [comment]
@apoelstra looks like PR 123 didn't make it to the changelog not sure what happened there. I raise the point for the sake of documentation :)

**Comment by tankyleo** [comment]
Is the changelog manually written, or is there a script that missed the PR ?

**Comment by tcharding** [comment]
Its manually written by me, I'm not sure what I was thinking when I skipped over that one. Feel free to PR patching the `CHANGELOG` if you want it added.

**Comment by tankyleo** [comment]
ah no problem I leave the decision to you all good with me thank you for the clarification.

**Comment by tcharding** [comment]
No stress man, sorry to rob you of your mention.

**Comment by tankyleo** [comment]
no problem at all, i'm learning how things work here :)

**Pull request merged**
