### PR TITLE
Add examples

### PR DESCRIPTION
**Pull request by tcharding**
Excludes patch 1 (#21).

Add additional examples. Patches 2-4 are preparatory cleanup.

### CODE REVIEW

**Comment by apoelstra** [comment]
I"m tempted to blanket-impl both `Debug` and `Display` on all implementors of this trait, passing through to `LowerHex`. Though I could imagine that causing issues down the line.

**Review by apoelstra — APPROVED** [review]
ACK b97b21aed7090a0c5666987caef9f4482557fa57

**Comment by apoelstra** [comment]
Will hold off on merging and give @Kixunil 72 hours to chime in. Though I really think that adding `Debug` impls on stuff is non-controversial, especially as it's a non-breaking change to modify their output.

**Comment by tcharding** [comment]
I pulled the trait bounds stuff out into #21 because I want to play with these examples a bit more.

**Comment by tcharding** [comment]
> I"m tempted to blanket-impl both Debug and Display on all implementors of this trait, passing through to LowerHex. 

That is definitely something that can be done in a future version, right? v0.1.0 is ok like this I rekon.

**Comment by tcharding** [comment]
I'm not clear on how to move forward on this now. I'll re-read the thread tomorrow but if you want to please say.

**Comment by tcharding** [comment]
> I"m tempted to blanket-impl both Debug and Display on all implementors of this trait, passing through to LowerHex.

On further thought, and after doing the wrap array examples this might be quite useful to differentiate between the two ways to use the lib a) impl fmt traits (and you do not get the default/display impls so you can control them yoursef) or implement the trait and get default/display impls.

> Though I could imagine that causing issues down the line.

Is this still a concern after my comment above?

**Comment by tcharding** [comment]
> I"m tempted to blanket-impl both Debug and Display on all implementors of this trait, passing through to LowerHex.

This does not apply now that we have the two `wrap_array_*` examples showing the two ways to use the display module, right?

**Comment by apoelstra** [comment]
> This does not apply now that we have the two `wrap_array_*` examples showing the two ways to use the display module, right?

No, it was just an idle thought.

**Review by apoelstra — APPROVED** [review]
ACK 96fd379d08f0578ad22fe0564557caad840814f7

**Pull request merged**
