### PR TITLE
Fix `HexToBytesIter::size_hint`

### PR DESCRIPTION
**Pull request by tankyleo**
`HexToBytesIter` iterates once for each pair of hex digits.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 81d72c4824d1ecc0c7ad78ff3d69953f1430b46f; successfully ran local tests; good catch!

**Comment by tcharding** [comment]
I wrote these two tests to convince myself the patch was correct, want to add them?

```rust

    #[test]
    fn hex_to_digits_size_hint() {
        let hex = "deadbeef";
        let iter = HexDigitsIter::new_unchecked(hex.as_bytes());
        // HexDigitsIter yields two digits at a time `[u8; 2]`.
        assert_eq!(iter.size_hint(), (4, Some(4)));

    }

    #[test]
    fn hex_to_bytes_size_hint() {
        let hex = "deadbeef";
        let iter = HexToBytesIter::new_unchecked(hex);
        assert_eq!(iter.size_hint(), (4, Some(4)));
    }
```

**Comment by tcharding** [comment]
And I confirmed that the second one fails on `master`.

**Comment by tankyleo** [comment]
Yes will add them thank you ! Let me know if you want me to pull the 'len' tests I added into their own standalone tests.

**Comment by tankyleo** [comment]
Rebase: add tests from Tobin.

**Review by tcharding — APPROVED** [review]
ACK 97870623de343f881e28c17377030fb1a1448f53

**Comment by tcharding** [comment]
Its good like this, thanks for finding this. We tried pretty hard with these iterators so its nice to have bugs removed.

**Pull request merged**
