### PR TITLE
Re-work CI

### PR DESCRIPTION
**Pull request by tcharding**
Re-work CI by doing, as individual patches

- Add two lock files (done separately because of change to the manifest)
- Add a script to update the lock files
- Add a justfile
- Fix lint warnings in `fuzz/`
- Re-write CI to use `run_task` from `rust-bitcoin-maintainer-tools`
- Run the fuzzer daily

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK a4b4f5e0a25c83c554603121c9d135a3557ccb34 successfully ran local tests

**Comment by apoelstra** [comment]
Let's give Kix a full two weeks unless we need this for some reason. This crate is pretty low-activity.

**Comment by tcharding** [comment]
Fair, cheers.

**Comment by tcharding** [comment]
Merge please mate, @Kixunil has had 2 weeks now.

**Pull request merged**
