### PR TITLE
Fix `Display` width and precision of `DisplayByteSlice`

### LINKED ISSUE #70: `max` is divided by 2
EDIT: Probably not worth reading this issue, just see #71

I'm pretty sure this line of code is wrong but I can't come up with a unit test to prove it. Patching it to what I think it should be does not break any unit tests.

https://github.com/rust-bitcoin/hex-conservative/blob/7116a460ad2dbf6b2aea9f37ebc933db79927c07/src/display.rs#L169

We are dividing the max string length by 2 as well as multiplying the number of bytes by 2 - we should just do one (I believe).

```rust
            let string_len = match f.precision() {
                Some(max) if self.bytes.len() * 2 > (max + 1) / 2 => max,
                Some(_) | None => self.bytes.len() * 2,
            };
```

Should be I think

```rust
```rust
            let string_len = match f.precision() {
                Some(max) if self.bytes.len() * 2 > max => max,
                Some(_) | None => self.bytes.len() * 2,
            };
```

### LINKED ISSUE #83: `DisplayHex` impls have different behaviours for different types
`DisplayArray`, `DisplayByteSlice`, and `fmt_hex_exact` each behave differently, this is surprising.

For example, how they handle `Formatter::precision`.

### PR DESCRIPTION
**Pull request by tankyleo**
Fixes #70

Also joins the implementation of `Display` for `DisplayByteSlice` and `DisplayArray`.

Partially addresses #83

### CODE REVIEW

**Comment by tankyleo** [comment]
No rush here.

- Tobin, I added you as co-author to eb1599b, how does that sound ? You had worked on this previously, the difference here is that this honors odd-length precision.
- The display of `fmt_hex_exact` is not yet consistent with `DisplayByteSlice` and `DisplayArray`. As a follow-up to this PR, we could have `internal_display` be written in terms of a `T: IntoIterator`, and have `fmt_hex_exact_fn` call `internal_display`

**Comment by tcharding** [comment]
> Tobin, I added you as co-author to https://github.com/rust-bitcoin/hex-conservative/commit/eb1599b63a656f99f0542eddb7e76f6125399866, how does that sound ? You had worked on this previously, the difference here is that this honors odd-length precision.

No attribution required, I'll do review for you though :)

**Review by apoelstra — APPROVED** [review]
ACK addb8046d0758047925c55b6fe72e69a731c2761 successfully ran local tests

**Review by tcharding — APPROVED** [review]
ACK addb8046d0758047925c55b6fe72e69a731c2761

**Pull request merged**
