### PR TITLE
Bump version to 0.1.1

### PR DESCRIPTION
**Pull request by tcharding**
- Patch 1 is #25, required for this release.
- Patch 2 bumps the version and adds changelog.

### CODE REVIEW

**Comment by apoelstra** [comment]
I think we could probably get away with 0.1.1. But up to you.

**Comment by tcharding** [comment]
Number go up!

**Comment by tcharding** [comment]
Not sure why I have been so confused for the last few years, this seems straight forward enough

> Initial development releases starting with “0.y.z” can treat changes in “y” as a major release, and “z” as a minor release.

https://doc.rust-lang.org/cargo/reference/semver.html

Changed to use v0.1.1 - note the branch name is now incorrect.

**Comment by apoelstra** [comment]
> Not sure why I have been so confused for the last few years, this seems straight forward enough

I am really fascinated to know what made this click for you. I feel like Kix and I have said that exact sentence before.

In any case, ack using 1.1 :)

**Comment by tcharding** [comment]
> I am really fascinated to know what made this click for you. I feel like Kix and I have said that exact sentence before.

If you ever work out how my brain works I'll be first in line to hear it. 90% of the time it feels like a well oiled machine and then it has these gaping holes in it, I am constantly baffled by the workings of the human mind.

**Comment by tcharding** [comment]
I think it has something to do with "tunnel vision", so slightly unrelated, but yesterday I was at an area and talking about a kids park, I pointed to where I thought it was. A few minutes later, after walking some more, I looked over again and the park was exactly next to where I had pointed and I had not seen it. The visual system is not the whole brain but these sorts of fails highlight similar workings I rekon. I get the sense that our brains actually do a lot less than we think (i.e., process way less visual inputs in this case) but in a way that makes them seem like they are doing alot.

**Review by apoelstra — APPROVED** [review]
ACK 42f3cdad67fd7f3a07058c5e231aaf4b12d453aa

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
